import type { Restaurant, Category, Product } from './types';

export const RESTAURANT: Restaurant = {
  id: 'r_01',
  slug: 'frita-e-fino',
  name: 'Frita & Fino',
  tagline: 'Salgaderia artesanal — fritos na hora, do jeitinho da vovó',
  cuisine: 'Salgados artesanais',
  logo: 'https://images.unsplash.com/photo-1625398407796-0fd2d60d5d26?w=200&h=200&fit=crop',
  cover: 'https://images.unsplash.com/photo-1628191081091-b7c524f2a81b?w=1600&h=900&fit=crop',
  rating: 4.8,
  ratingCount: 3214,
  address: 'Av. Paulista, 2100 — Bela Vista, São Paulo',
  timezone: 'America/Sao_Paulo',
  primary: '#B93C10',
  accent: '#FFB020',
  serviceFeePct: 10,
};

export const CATEGORIES: Category[] = [
  { id: 'c_destaques', name: 'Mais Pedidos', icon: '🔥', order: 1,
    image: 'https://images.unsplash.com/photo-1628191081091-b7c524f2a81b?w=600&h=600&fit=crop' },
  { id: 'c_fritos', name: 'Salgados Fritos', icon: '🥟', order: 2,
    image: 'https://images.unsplash.com/photo-1625398407796-0fd2d60d5d26?w=600&h=600&fit=crop' },
  { id: 'c_mini', name: 'Mini Salgados', icon: '🍘', order: 3,
    image: 'https://images.unsplash.com/photo-1625944525903-8e91e4d8ec31?w=600&h=600&fit=crop' },
  { id: 'c_combos', name: 'Combos & Kits Festa', icon: '🎉', order: 4,
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=600&h=600&fit=crop' },
  { id: 'c_assados', name: 'Salgados Assados', icon: '🥐', order: 5,
    image: 'https://images.unsplash.com/photo-1549203436-f3f5a16fa2e9?w=600&h=600&fit=crop' },
  { id: 'c_doces', name: 'Docinhos', icon: '🍬', order: 6,
    image: 'https://images.unsplash.com/photo-1578775887804-699de7086ff9?w=600&h=600&fit=crop' },
  { id: 'c_bebidas', name: 'Bebidas', icon: '🥤', order: 7,
    image: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=600&h=600&fit=crop' },
];

export const PRODUCTS: Product[] = [
  // ====================== SALGADOS FRITOS (unitários) ======================
  {
    id: 'p_coxinha_catupiry',
    categoryId: 'c_fritos',
    name: 'Coxinha de Frango com Catupiry',
    description: 'A rainha da casa. Massa leve dourada por fora, recheio generoso de frango desfiado temperado e catupiry cremoso derretendo dentro. Cada coxinha pesa 90g.',
    price: 9.90,
    image: 'https://images.unsplash.com/photo-1625398407796-0fd2d60d5d26?w=900&h=600&fit=crop',
    tags: ['popular', 'assinatura'],
    allergens: ['gluten', 'lactose'],
    prepTimeMin: 4,
    calories: 220,
    rating: 4.9, ratingCount: 1240,
    available: true,
    featured: true,
    popular: true,
    modifierGroups: [
      {
        id: 'mg_ponto', name: 'Ponto da fritura', type: 'single', min: 1, max: 1,
        options: [
          { id: 'pt_normal', name: 'Padrão (dourado)', priceDelta: 0 },
          { id: 'pt_mais', name: 'Mais crocante (+1min)', priceDelta: 0 },
        ],
      },
      {
        id: 'mg_molho', name: 'Molho de acompanhamento', type: 'multi', min: 0, max: 3,
        options: [
          { id: 'ml_pimenta', name: 'Pimenta artesanal da casa', priceDelta: 3 },
          { id: 'ml_maionese', name: 'Maionese de ervas', priceDelta: 3 },
          { id: 'ml_barbecue', name: 'Barbecue defumado', priceDelta: 3 },
        ],
      },
    ],
  },
  {
    id: 'p_coxinha_frango',
    categoryId: 'c_fritos',
    name: 'Coxinha de Frango',
    description: 'Clássica coxinha de frango temperado com cheiro-verde, cebola e pimenta-do-reino. A receita que atravessou três gerações.',
    price: 8.50,
    image: 'https://images.unsplash.com/photo-1604326531570-2689ea7e7e02?w=900&h=600&fit=crop',
    tags: ['popular'],
    allergens: ['gluten'],
    prepTimeMin: 4,
    calories: 195,
    rating: 4.8, ratingCount: 842,
    available: true,
    popular: true,
  },
  {
    id: 'p_kibe',
    categoryId: 'c_fritos',
    name: 'Kibe Recheado',
    description: 'Kibe de trigo e carne bovina temperados com hortelã fresca, recheado com requeijão cremoso.',
    price: 9.00,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=900&h=600&fit=crop',
    tags: [],
    allergens: ['gluten', 'lactose'],
    prepTimeMin: 5,
    calories: 210,
    rating: 4.7, ratingCount: 412,
    available: true,
  },
  {
    id: 'p_bolinha_queijo',
    categoryId: 'c_fritos',
    name: 'Bolinha de Queijo',
    description: 'Massa crocante por fora, queijo muçarela derretido por dentro — impossível resistir a uma só.',
    price: 6.50,
    image: 'https://images.unsplash.com/photo-1625398407796-0fd2d60d5d26?w=900&h=600&fit=crop',
    tags: ['vegetariano', 'popular'],
    allergens: ['gluten', 'lactose'],
    prepTimeMin: 4,
    calories: 180,
    rating: 4.8, ratingCount: 681,
    available: true,
    popular: true,
  },
  {
    id: 'p_bolinho_bacalhau',
    categoryId: 'c_fritos',
    name: 'Bolinho de Bacalhau Portuense',
    description: 'Bacalhau desfiado, batata, cebola e salsa — receita portuguesa tradicional, frito na hora.',
    price: 11.90,
    image: 'https://images.unsplash.com/photo-1572807203067-5e5a8aeb9c68?w=900&h=600&fit=crop',
    tags: ['premium'],
    allergens: ['gluten', 'peixe', 'ovo'],
    prepTimeMin: 5,
    calories: 230,
    rating: 4.9, ratingCount: 267,
    available: true,
    featured: true,
  },
  {
    id: 'p_pastel_carne',
    categoryId: 'c_fritos',
    name: 'Pastel de Carne',
    description: 'Pastel crocante recheado com carne moída temperada, azeitona preta e cheiro-verde. Massa fininha, sequinha, do jeito que tem que ser.',
    price: 12.00,
    image: 'https://images.unsplash.com/photo-1625944525903-8e91e4d8ec31?w=900&h=600&fit=crop',
    tags: ['popular'],
    allergens: ['gluten', 'ovo'],
    prepTimeMin: 6,
    calories: 310,
    rating: 4.8, ratingCount: 523,
    available: true,
    popular: true,
  },
  {
    id: 'p_pastel_queijo',
    categoryId: 'c_fritos',
    name: 'Pastel de Queijo',
    description: 'Pastel recheado com queijo muçarela derretido e um toque de orégano.',
    price: 11.00,
    image: 'https://images.unsplash.com/photo-1601050690647-f9e7eda1cf09?w=900&h=600&fit=crop',
    tags: ['vegetariano'],
    allergens: ['gluten', 'lactose', 'ovo'],
    prepTimeMin: 6,
    calories: 290,
    rating: 4.7, ratingCount: 398,
    available: true,
  },
  {
    id: 'p_pastel_frango',
    categoryId: 'c_fritos',
    name: 'Pastel de Frango com Catupiry',
    description: 'Frango desfiado e catupiry cremoso dentro de um pastel crocante gigante.',
    price: 13.00,
    image: 'https://images.unsplash.com/photo-1625398407796-0fd2d60d5d26?w=900&h=600&fit=crop',
    tags: [],
    allergens: ['gluten', 'lactose', 'ovo'],
    prepTimeMin: 6,
    calories: 320,
    rating: 4.8, ratingCount: 287,
    available: true,
  },
  {
    id: 'p_risole_camarao',
    categoryId: 'c_fritos',
    name: 'Risole de Camarão',
    description: 'Massa delicada empanada, recheio cremoso de camarão ao molho branco com toque de cebolinha.',
    price: 12.50,
    image: 'https://images.unsplash.com/photo-1625944525903-8e91e4d8ec31?w=900&h=600&fit=crop',
    tags: ['premium'],
    allergens: ['gluten', 'lactose', 'ovo', 'crustáceo'],
    prepTimeMin: 5,
    calories: 240,
    rating: 4.8, ratingCount: 189,
    available: true,
  },
  {
    id: 'p_croquete',
    categoryId: 'c_fritos',
    name: 'Croquete de Carne Seca',
    description: 'Carne seca desfiada, abóbora amassada e queijo coalho — uma explosão de nordeste.',
    price: 10.50,
    image: 'https://images.unsplash.com/photo-1625944227005-dd12ef2cf6eb?w=900&h=600&fit=crop',
    tags: ['novidade'],
    allergens: ['gluten', 'lactose', 'ovo'],
    prepTimeMin: 5,
    calories: 260,
    rating: 4.9, ratingCount: 124,
    available: true,
  },
  {
    id: 'p_enroladinho',
    categoryId: 'c_fritos',
    name: 'Enroladinho de Salsicha',
    description: 'Salsicha envolta em massa macia, frita até ficar dourada — o preferido da criançada.',
    price: 7.50,
    image: 'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=900&h=600&fit=crop',
    tags: [],
    allergens: ['gluten'],
    prepTimeMin: 4,
    calories: 200,
    rating: 4.6, ratingCount: 312,
    available: true,
  },
  {
    id: 'p_coxinha_vegana',
    categoryId: 'c_fritos',
    name: 'Coxinha Vegana de Jaca',
    description: 'Jaca desfiada temperada com cheiro-verde, massa sem leite nem ovos. Totalmente vegetal, totalmente viciante.',
    price: 11.90,
    image: 'https://images.unsplash.com/photo-1625398407796-0fd2d60d5d26?w=900&h=600&fit=crop',
    tags: ['vegano', 'novidade'],
    allergens: ['gluten'],
    prepTimeMin: 5,
    calories: 190,
    rating: 4.7, ratingCount: 98,
    available: true,
  },

  // ====================== MINI SALGADOS (venda por cento) ======================
  {
    id: 'p_mini_sortido_100',
    categoryId: 'c_mini',
    name: 'Cento de Mini Salgados Sortidos',
    description: '100 mini salgados fritos artesanais: coxinha, kibe, bolinha de queijo, risole e enroladinho. Entregamos crus congelados ou fritos na hora.',
    price: 179.00,
    image: 'https://images.unsplash.com/photo-1625944525903-8e91e4d8ec31?w=900&h=600&fit=crop',
    tags: ['festa', 'popular'],
    allergens: ['gluten', 'lactose', 'ovo'],
    prepTimeMin: 30,
    rating: 4.9, ratingCount: 428,
    available: true,
    featured: true,
    modifierGroups: [
      {
        id: 'mg_entrega', name: 'Forma de entrega', type: 'single', min: 1, max: 1,
        options: [
          { id: 'en_fritos', name: 'Fritos na hora (consumo imediato)', priceDelta: 0 },
          { id: 'en_crus', name: 'Crus congelados (levar para casa)', priceDelta: -10 },
        ],
      },
      {
        id: 'mg_sabores', name: 'Preferência de sabores (escolha até 4)', type: 'multi', min: 1, max: 4,
        options: [
          { id: 'sb_coxinha', name: 'Coxinha de frango', priceDelta: 0 },
          { id: 'sb_kibe', name: 'Kibe', priceDelta: 0 },
          { id: 'sb_queijo', name: 'Bolinha de queijo', priceDelta: 0 },
          { id: 'sb_risole', name: 'Risole de palmito', priceDelta: 0 },
          { id: 'sb_enrolado', name: 'Enroladinho de salsicha', priceDelta: 0 },
          { id: 'sb_pastel', name: 'Mini pastel de carne', priceDelta: 8 },
        ],
      },
    ],
  },
  {
    id: 'p_mini_200',
    categoryId: 'c_mini',
    name: '200 Mini Salgados Premium',
    description: 'Kit para festas médias: 200 salgados sortidos premium, incluindo camarão e bacalhau. Acompanha bandeja.',
    price: 389.00,
    image: 'https://images.unsplash.com/photo-1625944525903-8e91e4d8ec31?w=900&h=600&fit=crop',
    tags: ['festa', 'premium'],
    allergens: ['gluten', 'lactose', 'ovo', 'peixe', 'crustáceo'],
    prepTimeMin: 45,
    rating: 4.9, ratingCount: 87,
    available: true,
  },
  {
    id: 'p_mini_50_refri',
    categoryId: 'c_mini',
    name: 'Combo Casa — 50 Salgados + 2L Refri',
    description: '50 mini salgados sortidos + uma garrafa de 2L de refrigerante à sua escolha. Ideal para o almoço de domingo.',
    price: 109.00,
    image: 'https://images.unsplash.com/photo-1625944525903-8e91e4d8ec31?w=900&h=600&fit=crop',
    tags: ['combo', 'popular'],
    allergens: ['gluten', 'lactose', 'ovo'],
    prepTimeMin: 25,
    rating: 4.8, ratingCount: 231,
    available: true,
    discountPct: 12,
  },

  // ====================== COMBOS ======================
  {
    id: 'p_combo_duo',
    categoryId: 'c_combos',
    name: 'Combo Dupla — 6 salgados + 2 refri',
    description: '6 salgados à sua escolha + 2 latas de 350ml. O combo perfeito para o lanche da tarde a dois.',
    price: 59.90,
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=900&h=600&fit=crop',
    tags: ['combo', 'popular'],
    allergens: ['gluten', 'lactose'],
    prepTimeMin: 8,
    rating: 4.8, ratingCount: 412,
    available: true,
    featured: true,
    popular: true,
  },
  {
    id: 'p_combo_empresa',
    categoryId: 'c_combos',
    name: 'Combo Escritório — 30 salgados + bebidas',
    description: '30 salgados sortidos + 6 latas de refrigerante + 2L de suco natural. Pronto para a reunião da tarde.',
    price: 189.00,
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=900&h=600&fit=crop',
    tags: ['corporativo'],
    allergens: ['gluten', 'lactose', 'ovo'],
    prepTimeMin: 20,
    rating: 4.9, ratingCount: 178,
    available: true,
  },

  // ====================== ASSADOS ======================
  {
    id: 'p_empada_frango',
    categoryId: 'c_assados',
    name: 'Empada de Frango',
    description: 'Massa amanteigada assada e recheio cremoso de frango com azeitonas.',
    price: 8.90,
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=900&h=600&fit=crop',
    tags: ['assado'],
    allergens: ['gluten', 'lactose', 'ovo'],
    prepTimeMin: 3,
    calories: 240,
    rating: 4.8, ratingCount: 321,
    available: true,
  },
  {
    id: 'p_esfiha',
    categoryId: 'c_assados',
    name: 'Esfiha de Carne',
    description: 'Esfiha aberta assada com recheio de carne moída temperada com limão e cebola.',
    price: 7.50,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=900&h=600&fit=crop',
    tags: ['assado'],
    allergens: ['gluten'],
    prepTimeMin: 3,
    calories: 170,
    rating: 4.7, ratingCount: 245,
    available: true,
  },

  // ====================== DOCES ======================
  {
    id: 'p_brigadeiro',
    categoryId: 'c_doces',
    name: 'Brigadeiro Gourmet (unidade)',
    description: 'Brigadeiro artesanal feito com chocolate belga 70% e granulado belga.',
    price: 5.90,
    image: 'https://images.unsplash.com/photo-1612809075471-1dda7b1ed65f?w=900&h=600&fit=crop',
    tags: ['doce', 'popular'],
    allergens: ['lactose'],
    prepTimeMin: 1,
    calories: 120,
    rating: 4.9, ratingCount: 512,
    available: true,
  },
  {
    id: 'p_beijinho',
    categoryId: 'c_doces',
    name: 'Beijinho Gourmet (unidade)',
    description: 'Beijinho cremoso de coco queimado com toque de baunilha natural.',
    price: 5.90,
    image: 'https://images.unsplash.com/photo-1578775887804-699de7086ff9?w=900&h=600&fit=crop',
    tags: ['doce'],
    allergens: ['lactose'],
    prepTimeMin: 1,
    calories: 115,
    rating: 4.8, ratingCount: 298,
    available: true,
  },

  // ====================== BEBIDAS ======================
  {
    id: 'p_coca',
    categoryId: 'c_bebidas',
    name: 'Coca-Cola 350ml',
    description: 'Lata gelada de Coca-Cola.',
    price: 7.00,
    image: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=900&h=600&fit=crop',
    tags: [],
    allergens: [],
    prepTimeMin: 1,
    rating: 4.9, ratingCount: 1892,
    available: true,
  },
  {
    id: 'p_guarana',
    categoryId: 'c_bebidas',
    name: 'Guaraná Antarctica 350ml',
    description: 'Lata gelada de Guaraná Antarctica.',
    price: 7.00,
    image: 'https://images.unsplash.com/photo-1581636625402-29b2a704ef13?w=900&h=600&fit=crop',
    tags: [],
    allergens: [],
    prepTimeMin: 1,
    rating: 4.7, ratingCount: 1248,
    available: true,
  },
  {
    id: 'p_suco_laranja',
    categoryId: 'c_bebidas',
    name: 'Suco de Laranja Natural 400ml',
    description: 'Suco de laranja pêra feito na hora, sem adição de açúcar.',
    price: 12.00,
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=900&h=600&fit=crop',
    tags: ['vegano', 'natural'],
    allergens: [],
    prepTimeMin: 3,
    calories: 180,
    rating: 4.8, ratingCount: 456,
    available: true,
  },
  {
    id: 'p_agua',
    categoryId: 'c_bebidas',
    name: 'Água Mineral 500ml',
    description: 'Água mineral sem gás gelada.',
    price: 5.00,
    image: 'https://images.unsplash.com/photo-1553530979-cc9cc3f2e7ab?w=900&h=600&fit=crop',
    tags: [],
    allergens: [],
    prepTimeMin: 1,
    rating: 4.9, ratingCount: 892,
    available: true,
  },
];

export function getCategory(id: string) {
  return CATEGORIES.find(c => c.id === id);
}

export function getProduct(id: string) {
  return PRODUCTS.find(p => p.id === id);
}

export function productsByCategory(categoryId: string) {
  if (categoryId === 'c_destaques') return PRODUCTS.filter(p => p.popular || p.featured);
  return PRODUCTS.filter(p => p.categoryId === categoryId);
}

export function featuredProducts() {
  return PRODUCTS.filter(p => p.featured);
}

export function popularProducts() {
  return PRODUCTS.filter(p => p.popular);
}
